# Generated by Django 4.2.7 on 2023-11-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('isStudent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('srcImgCompany', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('remuneration', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
                ('softSkills', models.CharField(max_length=50)),
                ('domains', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
